#!/usr/bin/env python3
"""Check versioned names through an explicit, reviewable compatibility list.

Protocol/schema and frozen-run identifiers are business contracts, not generic
permission to use revision suffixes. Every retained occurrence therefore has
to identify its exact path, symbol, rationale, and removal phase here.
"""

from __future__ import annotations

import re
from pathlib import Path


VERSIONED_NAME = re.compile(r"\b[A-Za-z_][A-Za-z0-9_]*_v[0-9]+\b")


def _entry(path: str, symbol: str, why: str, removal_phase: str) -> dict:
    return {
        "path": path,
        "symbol": symbol,
        "why_allowed": why,
        "removal_phase": removal_phase,
    }


ALLOWLIST = (
    _entry("python/planning/contracts/task.py", "formal_v2", "formal Pre-BC task-contract mode is an artifact identity", "NEVER_TASK_CONTRACT_COMPATIBILITY"),
    _entry("python/planning/contracts/task.py", "legacy_v1", "historical task-contract mode is an explicit compatibility identity", "DEFERRED_UNTIL_NEW_BC_EVALUATED"),
    _entry("python/planning/contracts/task.py", "validate_legacy_task_contract_v1", "explicit V1 validator prevents silent historical-to-formal upgrade", "DEFERRED_UNTIL_NEW_BC_EVALUATED"),
    _entry("python/planning/mission/spec.py", "historical_v1", "mission validation mode is an explicit frozen RL compatibility seam", "DEFERRED_UNTIL_NEW_BC_EVALUATED"),
    _entry("python/planning/mission/spec.py", "validate_legacy_task_contract_v1", "mission contract re-exports the explicit historical V1 validator", "DEFERRED_UNTIL_NEW_BC_EVALUATED"),
    _entry("python/planning/data/mission_routes.py", "mission_route_store_v1", "immutable route-store artifact contract remains readable for pre-BC provenance", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/protocol/command.py", "primitive_execution_command_v4", "canonical command wire owner preserves the frozen protocol identity", "NEVER_PROTOCOL_COMPATIBILITY"),
    _entry("python/planning/protocol/result.py", "primitive_execution_schema_v4", "canonical result wire owner preserves the frozen protocol identity", "NEVER_PROTOCOL_COMPATIBILITY"),
    _entry("python/planning/protocol/snapshot.py", "endpoint_observation_snapshot_v4", "canonical snapshot wire owner preserves the frozen protocol identity", "NEVER_PROTOCOL_COMPATIBILITY"),
    _entry("python/planning/protocol/validation.py", "primitive_execution_command_v4", "protocol validation preserves the frozen command identity", "NEVER_PROTOCOL_COMPATIBILITY"),
    _entry("python/planning/protocol/validation.py", "primitive_execution_schema_v4", "protocol validation preserves the frozen result identity", "NEVER_PROTOCOL_COMPATIBILITY"),
    _entry("python/planning/contracts/awac_handoff.py", "awac_bc_to_rl_handoff_provenance_v1", "AWAC handoff artifact contract identity remains checkpoint-compatible", "DEFERRED_UNTIL_NEW_BC_EVALUATED"),
    _entry("python/planning/contracts/pipeline_provenance.py", "planning_py2_producer_provenance_v1", "PY2 producer provenance schema is an active artifact contract", "DEFERRED_UNTIL_NEW_BC_EVALUATED"),
    _entry("python/planning/data/csv_journal.py", "csv_journal_v1", "append-only journal artifact contract remains readable for recovery", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/data/voxel_cache.py", "historical_collision_checker_two_pass_voxelization_v1", "voxel-cache metadata records the exact historical two-pass algorithm used as the semantic generation contract", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/diagnostics/reliable_single_worker.py", "primitive_execution_command_v4", "reliable Unity command wire module is frozen protocol compatibility", "NEVER_PROTOCOL_COMPATIBILITY"),
    _entry("python/planning/evaluation/policy_evaluator.py", "missing_v4", "reliable-v4 evaluation diagnostic field names the frozen runtime path", "DEFERRED_UNTIL_NEW_BC_EVALUATED"),
    _entry("python/planning/evaluation/policy_evaluator.py", "policy_unity_evaluation_observation_provenance_v1", "evaluation observation provenance artifact contract identity", "DEFERRED_UNTIL_NEW_BC_EVALUATED"),
    _entry("python/planning/evaluation/policy_evaluator.py", "reliable_v4", "reliable-v4 evaluation option and output fields are frozen runtime contract", "DEFERRED_UNTIL_NEW_BC_EVALUATED"),
    _entry("python/planning/protocol/endpoint_observation_snapshot_v4.py", "primitive_execution_schema_v4", "endpoint snapshot wire schema compatibility", "NEVER_PROTOCOL_COMPATIBILITY"),
    _entry("python/planning/protocol/primitive_execution_command_v4.py", "primitive_execution_schema_v4", "primitive command/result wire schema compatibility", "NEVER_PROTOCOL_COMPATIBILITY"),
    _entry("python/planning/common/checkpoint_evidence.py", "p3_frozen_checkpoint_evidence_v1", "historical P3 checkpoint evidence schema must remain readable", "DEFERRED_UNTIL_NEW_BC_EVALUATED"),
    _entry("python/planning/runtime/bridge_identity.py", "bridge_source_manifest_v1", "bridge source manifest binds the frozen native artifact identity", "DEFERRED_UNTIL_NEW_BC_EVALUATED"),
    _entry("python/planning/mission/preparation.py", "formal_teacher_mission_preparation_v1", "formal mission-preparation orchestration contract binds resumable pre-BC artifacts", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/mission/preparation.py", "flight_reliable_exact_teacher_20260829_v2", "default formal run directory is an explicit artifact identity, not a language or API name", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/runtime/identity.py", "p3_runtime_identity_manifest_v1", "runtime identity manifest is required for historical P3 provenance", "DEFERRED_UNTIL_NEW_BC_EVALUATED"),
    _entry("python/planning/runtime/identity.py", "pre_collection_runtime_final_v3", "canonical pre-collection runtime identity artifact used by the formal CLI gate", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/runtime/identity.py", "primitive_result_v4", "runtime identity names the frozen primitive result protocol", "NEVER_PROTOCOL_COMPATIBILITY"),
    _entry("python/planning/runtime/identity.py", "reliable_command_v4", "runtime identity names the frozen reliable command protocol", "NEVER_PROTOCOL_COMPATIBILITY"),
    _entry("python/planning/runtime/identity.py", "reset_v4", "runtime identity names the frozen reset protocol", "NEVER_PROTOCOL_COMPATIBILITY"),
    _entry("python/planning/runtime/identity.py", "snapshot_v4", "runtime identity names the frozen snapshot protocol", "NEVER_PROTOCOL_COMPATIBILITY"),
    _entry("python/planning/runtime/lifecycle.py", "reliable_v4_runtime_instance_lifecycle_v1", "worker lifecycle manifest contract binds reliable runtime ownership", "DEFERRED_UNTIL_NEW_BC_EVALUATED"),
    _entry("python/planning/runtime/managed_runtime.py", "planning_managed_runtime_lifecycle_v1", "shared managed ROS Unity Bridge lifecycle manifest contract", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/runtime/managed_runtime.py", "reliable_v4", "managed runtime mode preserves the frozen reliable transport path", "DEFERRED_UNTIL_NEW_BC_EVALUATED"),
    _entry("scripts/run_managed_runtime.py", "reliable_v4", "shared managed runtime entrypoint preserves the frozen reliable transport mode", "DEFERRED_UNTIL_NEW_BC_EVALUATED"),
    _entry("python/planning/runtime/ports.py", "p3_worker_runtime_spec_v2", "historical worker port profile remains compatible with evidence", "DEFERRED_UNTIL_NEW_BC_EVALUATED"),
    _entry("python/planning/runtime/reliable_endpoint_snapshot_provider.py", "endpoint_observation_snapshot_v4", "endpoint snapshot provider imports the frozen reliable protocol module", "NEVER_PROTOCOL_COMPATIBILITY"),
    _entry("python/planning/runtime/reliable_endpoint_snapshot_provider.py", "primitive_execution_schema_v4", "endpoint snapshot provider validates the frozen result schema", "NEVER_PROTOCOL_COMPATIBILITY"),
    _entry("python/planning/runtime/reliable_unity_env_backend.py", "primitive_execution_command_v4", "reliable environment backend imports the frozen command wire module", "NEVER_PROTOCOL_COMPATIBILITY"),
    _entry("python/planning/runtime/reliable_unity_env_backend.py", "primitive_execution_schema_v4", "reliable environment backend validates the frozen result schema", "NEVER_PROTOCOL_COMPATIBILITY"),
    _entry("python/planning/runtime/unity_env.py", "reliable_v4", "Unity environment runtime mode and observation metadata remain frozen", "DEFERRED_UNTIL_NEW_BC_EVALUATED"),
    _entry("python/planning/teacher/rollout_session.py", "reliable_v4", "Teacher rollout session records the frozen reliable observation mode", "DEFERRED_UNTIL_NEW_BC_EVALUATED"),
    _entry("scripts/evaluate_policy_unity_managed.sh", "reliable_v4", "managed evaluation shell seam preserves the frozen reliable mode fields", "DEFERRED_UNTIL_NEW_BC_EVALUATED"),
    _entry("scripts/aggregate_bc_scale_evaluation.py", "reliable_v4", "scale-comparison report validates the frozen reliable runtime field without changing its contract", "DEFERRED_UNTIL_NEW_BC_EVALUATED"),
    _entry("scripts/aggregate_bc_scale_evaluation.py", "bc_data_scale_closed_loop_comparison_v1", "BC scale comparison output is an explicit report artifact schema", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/awac/checkpoint.py", "awac_checkpoint_schema_v2", "AWAC checkpoint schema is an active resume artifact contract", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/awac/checkpoint.py", "awac_checkpoint_schema_v3", "AWAC checkpoint schema v3 adds the exact-resume transaction contract", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/awac/checkpoint.py", "awac_calibration_exact_resume_state_v1", "exact-resume state is an active checkpoint artifact schema", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/awac/checkpoint.py", "awac_calibration_checkpoint_transaction_v1", "checkpoint/replay commit marker is an active recovery artifact schema", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/awac/checkpoint.py", "awac_calibration_checkpoint_transaction_diagnostics_v1", "checkpoint transaction diagnostics are active recovery evidence", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/awac/checkpoint.py", "awac_calibration_replay_pending_generation_v1", "replay pending-generation journal is an active recovery artifact schema", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/awac/checkpoint.py", "awac_calibration_holdout_records_v1", "ordered raw holdout evidence is an active exact-resume artifact schema", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/awac/calibration.py", "awac_checkpoint_schema_v2", "critic-calibration checkpoint payload preserves the active AWAC resume schema", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/awac/calibration.py", "awac_calibration_gate_v2", "future calibration value-certification gate is an explicit versioned contract", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/awac/calibration.py", "episode_monte_carlo_return_v1", "complete-episode holdout return semantics are an explicit calibration evidence contract", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/awac/calibration.py", "awac_calibration_gate_legacy_v1", "legacy calibration gate metadata remains readable without auto-upgrade", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/awac/phase1.py", "awac_phase1_readiness_v1", "Phase-1 readiness and calibration control-flow contract", "DEFERRED_UNTIL_NEW_BC_EVALUATED"),
    _entry("scripts/benchmark_awac_actor_depth_lr.py", "awac_actor_depth_lr_sanity_v1", "bounded offline Actor depth-learning-rate sanity artifact", "DEFERRED_UNTIL_NEW_BC_EVALUATED"),
    _entry("python/planning/awac/confidence.py", "awac_confidence_interface_v1", "confidence is an explicit typed future owner seam", "DEFERRED_UNTIL_AWAC_PHASE_0"),
    _entry("python/planning/awac/confidence.py", "awac_twin_q_confidence_v1", "Twin-Q confidence computation contract for the proposed-method foundation", "DEFERRED_UNTIL_NEW_BC_EVALUATED"),
    _entry("python/planning/awac/adaptive_bc_kl.py", "awac_adaptive_bc_kl_v1", "adaptive BC-KL weighting contract for the proposed-method foundation", "DEFERRED_UNTIL_NEW_BC_EVALUATED"),
    _entry("python/planning/awac/learner.py", "awac_twin_q_confidence_v1", "learner serialization preserves the Twin-Q confidence foundation identity", "DEFERRED_UNTIL_NEW_BC_EVALUATED"),
    _entry("python/planning/awac/learner.py", "awac_adaptive_bc_kl_v1", "learner serialization preserves the adaptive BC-KL foundation identity", "DEFERRED_UNTIL_NEW_BC_EVALUATED"),
    _entry("python/planning/awac/primitive_exploration.py", "awac_primitive_exploration_v1", "primitive local-to-global behavior-policy foundation contract", "DEFERRED_UNTIL_NEW_BC_EVALUATED"),
    _entry("python/planning/awac/primitive_neighborhood.py", "awac_primitive_neighborhood_v1", "geometry-only primitive-neighborhood artifact contract", "DEFERRED_UNTIL_NEW_BC_EVALUATED"),
    _entry("python/planning/awac/primitive_neighborhood.py", "geometry_descriptor_v1", "primitive-neighborhood descriptor generator identity", "DEFERRED_UNTIL_NEW_BC_EVALUATED"),
    _entry("python/planning/awac/trainer.py", "awac_innovation_foundation_v1", "future proposed-method configuration identity", "DEFERRED_UNTIL_NEW_BC_EVALUATED"),
    _entry("python/planning/awac/trainer.py", "awac_twin_q_confidence_v1", "trainer records the Twin-Q confidence foundation identity", "DEFERRED_UNTIL_NEW_BC_EVALUATED"),
    _entry("python/planning/awac/trainer.py", "awac_adaptive_bc_kl_v1", "trainer records the adaptive BC-KL foundation identity", "DEFERRED_UNTIL_NEW_BC_EVALUATED"),
    _entry("python/planning/awac/trainer.py", "awac_primitive_exploration_v1", "trainer records the primitive exploration foundation identity", "DEFERRED_UNTIL_NEW_BC_EVALUATED"),
    _entry("python/planning/awac/contract.py", "discrete_masked_awac_checkpoint_v2", "AWAC checkpoint identity is an active algorithm artifact contract", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/awac/contract.py", "discrete_masked_awac_training_v2", "AWAC training configuration identity is an active artifact contract", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/awac/contract.py", "discrete_masked_awac_replay_uint8_v1", "AWAC replay storage identity is an active artifact contract", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/awac/trainer.py", "reliable_v4", "AWAC trainer preserves the frozen reliable runtime option", "DEFERRED_UNTIL_NEW_BC_EVALUATED"),
    _entry("python/planning/awac/trainer.py", "awac_checkpoint_schema_v2", "AWAC trainer emits the active checkpoint schema", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/awac/trainer.py", "awac_calibration_episode_split_v1", "critic-calibration trainer binds the deterministic episode split artifact", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/awac/calibration.py", "awac_formal_calibration_runtime_v1", "critic-calibration checkpoint records the active online runtime contract", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/awac/calibration_runtime.py", "awac_formal_calibration_runtime_v1", "formal online replay producer runtime contract", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/awac/calibration_runtime.py", "awac_calibration_episode_split_v1", "deterministic online calibration split artifact contract", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/awac/calibration_runtime.py", "frozen_bc_masked_categorical_t1_v1", "new calibration behavior-policy identity binds frozen BC masked categorical temperature-one collection", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/awac/calibration_runtime.py", "sha256_base_seed_worker_episode_mission_uint32_v1", "per-episode-per-worker calibration RNG derivation is persisted provenance", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/awac/checkpoint.py", "awac_formal_calibration_runtime_v1", "checkpoint validation preserves the online calibration runtime contract", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/awac/trainer.py", "awac_formal_calibration_run_v1", "formal online calibration run artifact contract", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/awac/trainer.py", "awac_formal_calibration_runtime_v1", "trainer persists the online calibration runtime contract", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/awac/trainer.py", "awac_calibration_runtime_failure_recovery_v1", "runtime failure recovery summary is an active diagnostic artifact schema", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/awac/trainer.py", "awac_phase0_calibration_smoke_v1", "bounded Phase-0 calibration smoke identifies its synthetic offline run contract", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/awac/checkpoint.py", "awac_standard_online_exact_resume_state_v1", "Standard AWAC exact-resume state is an active checkpoint artifact schema", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/awac/checkpoint.py", "awac_standard_online_runtime_v1", "Standard AWAC online runtime identity is an active artifact schema", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/awac/checkpoint.py", "awac_standard_online_resume_value_v1", "Standard AWAC exact-resume value hashing domain is an active checkpoint identity", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/awac/online_runtime.py", "awac_standard_online_runtime_v1", "Standard AWAC online runtime progress is an active artifact schema", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/awac/online_runtime.py", "awac_standard_online_summary_v1", "Standard AWAC online summary is an active artifact schema", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/awac/trainer.py", "awac_standard_online_run_v1", "Standard AWAC online run identity is an active artifact schema", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/awac/trainer.py", "awac_standard_online_runtime_v1", "Standard AWAC online checkpoint runtime schema is an active artifact schema", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/awac/trainer.py", "awac_standard_online_runtime_failure_v1", "Standard AWAC online runtime failure is an active diagnostic artifact schema", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/awac/trainer.py", "awac_standard_online_runtime_start_v1", "Standard AWAC online pre-runtime Actor identity is an active diagnostic artifact schema", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/evaluation/mission_split.py", "awac_dev_set_phase0_v1", "Phase-0 AWAC development-set artifact identity", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/evaluation/mission_split.py", "awac_calibration_episode_split_v1", "critic-calibration episode split artifact identity", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/evaluation/reliable_v4_baseline.py", "reliable_v4_fixed_dev_baseline_v1", "fixed development baseline identity is evidence-compatible", "DEFERRED_UNTIL_NEW_BC_EVALUATED"),
    _entry("python/planning/evaluation/reliable_v4_baseline.py", "reliable_command_v4", "baseline validates the frozen reliable command protocol identity", "NEVER_PROTOCOL_COMPATIBILITY"),
    _entry("python/planning/evaluation/reliable_v4_baseline.py", "primitive_result_v4", "baseline validates the frozen primitive result protocol identity", "NEVER_PROTOCOL_COMPATIBILITY"),
    _entry("python/planning/evaluation/reliable_v4_baseline.py", "snapshot_v4", "baseline validates the frozen snapshot protocol identity", "NEVER_PROTOCOL_COMPATIBILITY"),
    _entry("python/planning/evaluation/reliable_v4_baseline.py", "reset_v4", "baseline validates the frozen reset protocol identity", "NEVER_PROTOCOL_COMPATIBILITY"),
    _entry("python/planning/evaluation/reliable_v4_baseline.py", "reliable_v4", "baseline records the frozen reliable runtime mode", "DEFERRED_UNTIL_NEW_BC_EVALUATED"),
    _entry("python/planning/evaluation/reliable_v4_baseline.py", "p3_runtime_identity_manifest_v1", "historical P3 runtime identity manifest remains evidence-readable", "DEFERRED_UNTIL_NEW_BC_EVALUATED"),
    _entry("python/planning/primitives/neighbors.py", "motion_primitive_neighbor_index_v1", "future primitive-neighbor artifact identity is an explicit owner seam", "DEFERRED_UNTIL_AWAC_PHASE_0"),
    _entry("scripts/compare_paired_policy_evaluations.py", "paired_policy_evaluation_v1", "paired BC/AWAC holdout comparison output is an explicit report artifact schema", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/diagnose_awac10k_targeted_trace.py", "flat_v7", "targeted critic diagnosis keeps the frozen V7 calibration comparison namespace", "DEFERRED_UNTIL_NEW_BC_EVALUATED"),
    _entry("scripts/diagnose_awac10k_targeted_trace.py", "centered_v7", "targeted critic diagnosis keeps the frozen V7 calibration comparison namespace", "DEFERRED_UNTIL_NEW_BC_EVALUATED"),
    _entry("scripts/diagnose_awac10k_targeted_trace.py", "deltas_v7", "targeted critic diagnosis keeps the frozen V7 calibration comparison namespace", "DEFERRED_UNTIL_NEW_BC_EVALUATED"),
    _entry("scripts/diagnose_awac10k_targeted_trace.py", "raw_q_abs_p95_ratio_awac10k_over_v7", "targeted critic diagnosis records a fixed V7 versus AWAC10K artifact comparison", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/audit_awac_innovation.py", "awac_bc60k_formal_critic_calibration_v7", "offline foundation audit uses the frozen V7 calibration source", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/audit_awac_innovation.py", "standard_awac_10k_v2", "offline foundation audit compares the frozen Standard AWAC checkpoint", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/audit_awac_innovation.py", "standard_awac_update_ratio025_10k_v1", "offline foundation audit compares the frozen tuned control checkpoint", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/audit_awac_innovation.py", "innovation_v1", "offline foundation audit output namespace", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/audit_awac_innovation.py", "awac_offline_confidence_audit_v1", "offline confidence and critic-ranking audit report schema", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/audit_awac_innovation.py", "awac_offline_confidence_audit_v2", "offline confidence audit report uses explicit Q-argmax disagreement semantics", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/awac/confidence.py", "awac_twin_q_confidence_v2", "active Twin-Q confidence contract identity", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/awac/confidence.py", "delta_q_uncertainty_exp_v2", "active Delta-Q and uncertainty formula identity", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/awac/confidence.py", "valid_qmin_half_range_or_mad_plus_mean_u_v1", "active confidence scale identity", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/run_awac_implementation_recertification.py", "implementation_recertification_v1", "offline implementation recertification output namespace", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/run_awac_implementation_recertification.py", "awac_bc60k_formal_critic_calibration_v7", "recertification reads the frozen calibration artifact identity", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/run_awac_implementation_recertification.py", "innovation_v1", "recertification preserves the historical innovation artifact namespace", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/run_awac_implementation_recertification.py", "calibration_v7", "recertification run label identifies the frozen calibration checkpoint", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/run_awac_implementation_recertification.py", "standard_awac_10k_v2", "recertification reads the frozen Standard AWAC checkpoint", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/run_awac_implementation_recertification.py", "critic_lr03_10k_v1", "recertification preserves the historical LR03 run identity", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/run_awac_implementation_recertification.py", "standard_awac_critic_lr03_10k_v1", "recertification reads the frozen LR03 checkpoint directory", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/run_awac_implementation_recertification.py", "update_ratio025_10k_v1", "recertification preserves the historical update-ratio control identity", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/run_awac_implementation_recertification.py", "standard_awac_update_ratio025_10k_v1", "recertification reads the frozen update-ratio checkpoint directory", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/run_awac_implementation_recertification.py", "awac_twin_q_confidence_v1", "historical confidence identity is retained only as unverified evidence metadata", "DEFERRED_UNTIL_NEW_BC_EVALUATED"),
    _entry("scripts/run_awac_implementation_recertification.py", "not_replaced_by_v2", "historical formula values are not overwritten by the active v2 formula", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/run_awac_implementation_recertification.py", "awac_recovery_parity_v1", "offline constant-beta recovery parity artifact schema", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/run_awac_implementation_recertification.py", "awac_metric_definitions_v2", "offline metric definition artifact schema", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/run_awac_implementation_recertification.py", "awac_implementation_finding_matrix_v1", "offline finding matrix artifact schema", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/run_awac_implementation_recertification.py", "historical_formula_values_not_rewritten_with_v2", "historical and proposed formula outputs are stored in separate namespaces", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/run_awac_implementation_recertification.py", "awac_historical_run_validity_v1", "historical run validity artifact schema", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/run_awac_implementation_recertification.py", "awac_optimizer_actual_lr_audit_v1", "actual optimizer LR audit artifact schema", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/run_awac_implementation_recertification.py", "awac_actor_update_breakdown_v1", "actor update counter breakdown artifact schema", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/run_awac_implementation_recertification.py", "awac_production_offline_parity_v2", "production Replay and model offline parity artifact schema", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/run_awac_implementation_recertification.py", "confidence_contract_v2", "recertification confidence contract report schema", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/run_awac_implementation_recertification.py", "awac_confidence_contract_v2", "recertification confidence contract artifact schema", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/run_awac_implementation_recertification.py", "awac_rank_metrics_v2", "recertification rank metric artifact schema", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/run_awac_actor_only_ab_control.py", "awac_fixed_critic_actor_only_ab_control_v1", "fixed-Critic Actor-only A/B/C experiment manifest identity", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/run_awac_actor_only_ab_control.py", "awac_actor_only_evaluation_checkpoint_v1", "non-resumable Actor-only evaluation checkpoint artifact identity", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/run_awac_actor_only_ab_control.py", "awac_actor_only_control_state_v1", "state-hash domain for the fixed-Critic invariance proof", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/run_awac_actor_only_ab_control.py", "awac_actor_only_control_replay_v1", "read-only replay content-hash domain for the fixed-Critic experiment", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/run_awac_actor_only_ab_control.py", "awac_actor_only_ordered_values_v1", "ordered-ID hash domain for fixed train/holdout and Dev100 provenance", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/run_awac_actor_only_ab_control.py", "awac_actor_only_fixed_batch_indices_v1", "shared fixed train/trust batch-sequence artifact identity", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/run_awac_actor_only_ab_control.py", "awac_fixed_critic_actor_only_dev100_paired_v1", "paired Dev100 terminal-transition and comparison artifact identity", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/recertify_awac_value_returns.py", "awac_bc60k_formal_critic_calibration_v7", "value-return recertification reads the frozen calibration artifact identity", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/recertify_awac_value_returns.py", "value_return_recertification_v1", "read-only value-return diagnostic output namespace", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/recertify_awac_value_returns.py", "awac_value_return_probe_before_after_v1", "value-return regression evidence artifact schema", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/recertify_awac_value_returns.py", "awac_value_return_metric_definitions_v1", "value-return metric-definition artifact schema", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/recertify_awac_value_returns.py", "awac_value_return_offline_recertification_v1", "read-only checkpoint recertification artifact schema", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/recertify_awac_value_returns.py", "calibration_v7", "frozen calibration run label used only as an artifact identity", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/recertify_awac_value_returns.py", "awac_holdout_return_contract_v2", "current holdout-return contract report schema", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/recertify_awac_value_returns.py", "awac_calibration_gate_contract_report_v2", "current calibration-gate contract report schema", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/recertify_awac_value_returns.py", "awac_value_policy_alignment_v1", "policy-alignment evidence artifact schema", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/build_awac_primitive_neighborhood.py", "awac_primitive_neighborhood_v1", "primitive-neighborhood artifact generator and output identity", "DEFERRED_UNTIL_NEW_BC_EVALUATED"),
    _entry("python/planning/diagnostics/multi_action_replay.py", "multi_action_replay_v1", "diagnostic-only state/action ranking replay artifact schema is isolated from production AWAC replay", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/diagnostics/multi_action_ranking_critic.py", "multi_action_ranking_critic_v1", "Critic-only diagnostic ranking module identity is isolated from production AWAC", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/diagnostics/multi_action_ranking_critic.py", "mission_group_split_v1", "mission-grouped cross-fitting manifest identity is diagnostic-only", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/diagnostics/state_sufficiency.py", "state_sufficiency_mission_split_v1", "state sufficiency mission-level split manifest is diagnostic-only", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/diagnostics/state_sufficiency.py", "state_sufficiency_dataset_identity_v1", "state sufficiency input identity is diagnostic-only", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/diagnostics/state_sufficiency.py", "state_sufficiency_model_config_v1", "state sufficiency independent MLP configuration is diagnostic-only", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/diagnostics/state_sufficiency.py", "state_sufficiency_fold_metrics_v1", "state sufficiency cross-fitted metrics artifact is diagnostic-only", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/diagnostics/state_sufficiency.py", "state_sufficiency_bootstrap_v1", "state sufficiency mission-cluster bootstrap artifact is diagnostic-only", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/diagnostics/observation_information_audit.py", "observation_information_audit_v1", "observation information audit identity is diagnostic-only", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/diagnostics/observation_information_audit.py", "observation_feature_importance_v1", "observation feature importance artifact is diagnostic-only", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/diagnostics/observation_information_audit.py", "observation_component_metrics_v1", "observation component ablation artifact is diagnostic-only", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/diagnostics/observation_information_audit.py", "observation_temporal_metrics_v1", "observation temporal ablation artifact is diagnostic-only", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/diagnostics/observation_information_audit.py", "within_state_return_variance_v1", "within-state outcome variance artifact is diagnostic-only", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/diagnostics/observation_information_audit.py", "observation_information_bootstrap_v1", "observation information bootstrap artifact is diagnostic-only", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/diagnostics/temporal_observation_ranking.py", "temporal_observation_ranking_audit_v1", "causal temporal observation ranking audit identity is diagnostic-only", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/diagnostics/temporal_observation_ranking.py", "temporal_variant_metrics_v1", "temporal observation variant metrics are diagnostic-only", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/diagnostics/temporal_observation_ranking.py", "temporal_observation_bootstrap_v1", "temporal observation mission-cluster bootstrap is diagnostic-only", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/diagnostics/temporal_observation_ranking.py", "temporal_feature_ablation_v1", "temporal feature ablation artifact is diagnostic-only", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/diagnostics/temporal_observation_ranking.py", "state_sufficiency_audit_v1", "temporal audit reads the prior state sufficiency evidence namespace", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/diagnostics/temporal_observation_ranking.py", "temporal_observation_ranking_model_config_v1", "temporal observation ranking MLP configuration is diagnostic-only", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/diagnostics/action_formulation_audit.py", "action_formulation_audit_v1", "action formulation audit identity is diagnostic-only", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/diagnostics/action_formulation_audit.py", "action_formulation_action_analysis_v1", "action library and outcome analysis artifact is diagnostic-only", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/diagnostics/action_formulation_audit.py", "action_formulation_primitive_metrics_v1", "primitive descriptor ranking metrics are diagnostic-only", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/diagnostics/action_formulation_audit.py", "action_formulation_model_config_v1", "action formulation independent MLP configuration is diagnostic-only", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/diagnostics/action_formulation_audit.py", "action_outcome_separability_v1", "action distance outcome separability artifact is diagnostic-only", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/diagnostics/action_formulation_audit.py", "action_formulation_bootstrap_v1", "action formulation mission-cluster bootstrap is diagnostic-only", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/diagnostics/reward_horizon_audit.py", "reward_horizon_credit_assignment_audit_v1", "reward horizon and credit assignment audit identity is diagnostic-only", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/diagnostics/reward_horizon_audit.py", "reward_horizon_metrics_v1", "reward horizon metrics artifact is diagnostic-only", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/diagnostics/reward_horizon_audit.py", "short_horizon_surrogate_metrics_v1", "immediate-reward versus terminal-return surrogate metrics are diagnostic-only", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/diagnostics/reward_horizon_audit.py", "reward_horizon_model_config_v1", "reward horizon independent MLP configuration is diagnostic-only", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/diagnostics/reward_horizon_audit.py", "reward_horizon_bootstrap_v1", "reward horizon mission-cluster bootstrap is diagnostic-only", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/diagnostics/reward_horizon_audit.py", "reward_horizon_mission_split_v1", "reward horizon mission-level split is diagnostic-only", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/diagnostics/reward_horizon_audit.py", "reward_horizon_within_state_outcome_v1", "within-state reward horizon outcome variance is diagnostic-only", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/diagnostics/reward_horizon_audit.py", "state_sufficiency_audit_v1", "reward horizon audit reuses the prior state-sufficiency evidence namespace", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/collect_multi_action_replay.py", "multi_action_replay_v1", "diagnostic collector emits the explicit multi-action replay artifact identity", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/train_multi_action_ranking_critic.py", "multi_action_replay_v1", "ranking diagnostic reads the separate multi-action replay artifact only", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/train_multi_action_ranking_critic.py", "multi_action_ranking_critic_v1", "ranking diagnostic output identity is isolated from production AWAC", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/diagnostics/reward_provenance_audit.py", "reward_provenance_recovery_audit_v1", "read-only reward provenance recovery audit artifact identity", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/diagnostics/reward_provenance_audit.py", "episode_reward_sequence_v1", "validated recovered episode reward sequence artifact identity", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/diagnostics/reward_provenance_audit.py", "reward_credit_metrics_v1", "read-only reward credit assignment metrics artifact identity", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/audit_reward_provenance.py", "reward_provenance_recovery_audit_v1", "reward provenance recovery CLI output identity", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/audit_reward_provenance.py", "awac_bc60k_formal_critic_calibration_v7", "reward provenance audit reads the frozen calibration replay artifact", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/audit_reward_provenance.py", "multi_action_replay_v1", "reward provenance audit reads the diagnostic multi-action artifact", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/diagnostics/decision_state_completeness.py", "decision_state_completeness_audit_v1", "decision-state completeness is an isolated read-only diagnostic artifact", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/diagnostics/decision_state_completeness.py", "multi_action_replay_v1", "decision-state audit reads the diagnostic multi-action artifact", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/diagnostics/decision_state_completeness.py", "observation_information_audit_v1", "decision-state audit reads the prior observation-information evidence", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/audit_decision_state_completeness.py", "observation_information_audit_v1", "decision-state CLI input is the prior observation-information artifact", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/audit_decision_state_completeness.py", "reward_provenance_recovery_audit_v1", "decision-state CLI input is the prior reward provenance artifact", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/audit_decision_state_completeness.py", "decision_state_completeness_audit_v1", "decision-state CLI output identity", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/diagnostics/observation_augmentation_ranking.py", "observation_augmentation_ranking_audit_v1", "non-privileged observation augmentation ranking audit is diagnostic-only", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/diagnostics/observation_augmentation_ranking.py", "observation_augmentation_variant_metrics_v1", "observation augmentation variant metrics are diagnostic-only", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/diagnostics/observation_augmentation_ranking.py", "observation_augmentation_bootstrap_v1", "observation augmentation mission-cluster bootstrap is diagnostic-only", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/diagnostics/observation_augmentation_ranking.py", "observation_augmentation_feature_delta_v1", "observation augmentation feature delta artifact is diagnostic-only", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/diagnostics/observation_augmentation_ranking.py", "observation_augmentation_ranking_model_config_v1", "observation augmentation independent MLP configuration is diagnostic-only", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/diagnostics/observation_augmentation_ranking.py", "multi_action_replay_v1", "observation augmentation audit reads the isolated multi-action replay artifact", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/diagnostics/observation_augmentation_ranking.py", "observation_information_audit_v1", "observation augmentation audit reuses the fixed prior mission split", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/audit_observation_augmentation_ranking.py", "observation_augmentation_ranking_audit_v1", "observation augmentation CLI output identity", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/audit_observation_augmentation_ranking.py", "multi_action_replay_v1", "observation augmentation CLI reads the isolated multi-action replay artifact", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/audit_observation_augmentation_ranking.py", "observation_information_audit_v1", "observation augmentation CLI uses the fixed prior mission split", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/diagnostics/hierarchical_task_formulation.py", "hierarchical_task_formulation_audit_v1", "hierarchical task formulation audit identity is diagnostic-only", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/diagnostics/hierarchical_task_formulation.py", "hierarchical_action_clusters_v1", "hierarchical action cluster artifact is diagnostic-only", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/diagnostics/hierarchical_task_formulation.py", "hierarchical_trajectory_pattern_v1", "hierarchical trajectory pattern artifact is diagnostic-only", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/diagnostics/hierarchical_task_formulation.py", "hierarchical_failure_mode_analysis_v1", "hierarchical failure-mode artifact is diagnostic-only", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/audit_hierarchical_task_formulation.py", "hierarchical_task_formulation_audit_v1", "hierarchical task formulation CLI output identity", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/audit_hierarchical_task_formulation.py", "action_formulation_audit_v1", "hierarchical task formulation CLI reads the prior action-formulation evidence namespace", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/diagnostics/high_level_action_abstraction.py", "high_level_action_abstraction_audit_v1", "high-level action abstraction audit identity is diagnostic-only", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/diagnostics/high_level_action_abstraction.py", "high_level_action_mapping_v1", "high-level action mapping artifact is diagnostic-only", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/diagnostics/high_level_action_abstraction.py", "high_level_abstraction_metrics_v1", "high-level abstraction statistics artifact is diagnostic-only", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/diagnostics/high_level_action_abstraction.py", "high_level_ranking_metrics_v1", "high-level ranking comparison artifact is diagnostic-only", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/audit_high_level_action_abstraction.py", "hierarchical_task_formulation_audit_v1", "high-level abstraction CLI reads the preceding hierarchical evidence namespace", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/audit_high_level_action_abstraction.py", "action_formulation_audit_v1", "high-level abstraction CLI uses the preceding fixed action-ranking split", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/audit_high_level_action_abstraction.py", "high_level_action_abstraction_audit_v1", "high-level abstraction CLI output identity", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/diagnostics/offline_rl_feasibility.py", "offline_rl_feasibility_audit_v1", "offline RL feasibility audit identity is diagnostic-only", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/diagnostics/offline_rl_feasibility.py", "offline_rl_oracle_upper_bound_v1", "observed-action oracle upper-bound artifact is diagnostic-only", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/audit_offline_rl_feasibility.py", "offline_rl_feasibility_audit_v1", "offline RL feasibility CLI output identity", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/diagnostics/oracle_action_imitation.py", "oracle_action_imitation_feasibility_v1", "observed-action oracle imitation is a diagnostic-only artifact", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/diagnostics/oracle_action_imitation.py", "oracle_action_dataset_v1", "oracle action labels are an isolated diagnostic dataset", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/diagnostics/oracle_action_imitation.py", "oracle_action_imitation_policy_metrics_v1", "supervised oracle imitation metrics are diagnostic-only", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/diagnostics/oracle_action_imitation.py", "oracle_action_imitation_bootstrap_v1", "oracle imitation mission bootstrap is diagnostic-only", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/audit_oracle_action_imitation.py", "oracle_action_imitation_feasibility_v1", "oracle imitation CLI output identity", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/audit_oracle_action_imitation.py", "multi_action_replay_v1", "oracle imitation CLI reads the isolated multi-action diagnostic replay", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/audit_oracle_action_imitation.py", "offline_rl_feasibility_audit_v1", "oracle imitation CLI reads the prior observed-action feasibility evidence", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/diagnostics/memory_state_sufficiency.py", "memory_state_sufficiency_audit_v1", "historical-memory state sufficiency is a diagnostic-only artifact", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/diagnostics/memory_state_sufficiency.py", "memory_state_sufficiency_metrics_v1", "memory pairwise metrics are diagnostic-only", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/diagnostics/memory_state_sufficiency.py", "oracle_memory_action_metrics_v1", "memory oracle-action metrics are diagnostic-only", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/diagnostics/memory_state_sufficiency.py", "memory_state_sufficiency_bootstrap_v1", "memory mission bootstrap is diagnostic-only", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/audit_memory_state_sufficiency.py", "memory_state_sufficiency_audit_v1", "memory state sufficiency CLI output identity", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/audit_memory_state_sufficiency.py", "multi_action_replay_v1", "memory state sufficiency CLI reads the isolated multi-action diagnostic replay", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/audit_memory_state_sufficiency.py", "oracle_action_imitation_feasibility_v1", "memory state sufficiency CLI reads the prior oracle imitation evidence", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/diagnostics/bc_local_candidate_feasibility.py", "bc_local_candidate_rl_feasibility_audit_v1", "BC-local candidate coverage is a diagnostic-only artifact and never changes production action space", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/diagnostics/bc_local_candidate_feasibility.py", "bc_local_candidate_definition_v1", "deterministic mask-valid candidate definition is diagnostic-only", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/diagnostics/bc_local_candidate_feasibility.py", "bc_local_candidate_oracle_coverage_v1", "observed-action oracle coverage is diagnostic-only", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/diagnostics/bc_local_candidate_feasibility.py", "bc_local_candidate_recovery_coverage_v1", "observed success recovery coverage is diagnostic-only", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/diagnostics/bc_local_candidate_feasibility.py", "bc_local_candidate_gain_retention_v1", "observed return gain retention is diagnostic-only", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/diagnostics/bc_local_candidate_feasibility.py", "bc_local_candidate_distance_analysis_v1", "BC-relative primitive distance analysis is diagnostic-only", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/diagnostics/bc_local_candidate_feasibility.py", "bc_local_candidate_random_control_v1", "size-matched random candidate control is diagnostic-only", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/diagnostics/bc_local_candidate_feasibility.py", "bc_local_candidate_cluster_bootstrap_v1", "mission-cluster bootstrap for local candidates is diagnostic-only", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/diagnostics/bc_local_candidate_feasibility.py", "bc_local_candidate_integrity_audit_v1", "local candidate audit immutability evidence is diagnostic-only", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/diagnostics/bc_local_candidate_feasibility.py", "action_formulation_action_analysis_v1", "BC-local candidate audit reads the fixed action-formulation neighbor artifact", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/diagnostics/bc_local_candidate_feasibility.py", "action_formulation_primitive_metrics_v1", "BC-local candidate audit validates the fixed action-formulation evidence namespace", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/diagnostics/bc_local_candidate_feasibility.py", "offline_rl_oracle_upper_bound_v1", "BC-local candidate audit reads the prior observed-action oracle evidence", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/diagnostics/bc_local_candidate_feasibility.py", "local_candidate_rl_interface_v1", "future local-candidate interface is emitted only as a non-production design artifact", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/audit_bc_local_candidate_feasibility.py", "bc_local_candidate_rl_feasibility_audit_v1", "BC-local candidate feasibility CLI output identity", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/audit_bc_local_candidate_feasibility.py", "offline_rl_feasibility_audit_v1", "BC-local candidate CLI reads prior observed-action feasibility evidence", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/sac/contract.py", "bc_initialized_online_discrete_sac_v1", "new SAC mainline algorithm identity is an explicit off-policy artifact contract", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/sac/contract.py", "bc_initialized_discrete_sac_checkpoint_v1", "SAC checkpoint identity binds fresh twin-Q and BC initialization", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/sac/contract.py", "bc_initialized_discrete_sac_online_replay_v1", "SAC online replay identity is isolated from historical AWAC and diagnostic replays", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/sac/contract.py", "bc_initialized_discrete_sac_training_config_v1", "SAC resolved training configuration identity is an explicit artifact contract", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/sac/contract.py", "sac_masked_categorical_v1", "SAC masked-categorical policy identity preserves the 105-action production interface", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/sac/contract.py", "sac_masked_categorical_residual_v5", "V5 bounded residual-policy identity is an explicit isolated experiment contract", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/sac/contract.py", "frozen_bc_reference_v1", "frozen BC reference identity binds the SAC actor KL reference", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/sac/network.py", "bc_masked_categorical_t1_warmup_v1", "SAC pre-learning-start behavior policy identity is persisted in online replay", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/sac/network.py", "sac_masked_categorical_v1", "SAC online behavior policy identity is persisted in online replay", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/sac/runtime.py", "sha256_base_seed_worker_episode_mission_uint32_v1", "SAC per-episode behavior RNG derivation is persisted provenance", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/sac/checkpoint.py", "bc_initialized_discrete_sac_checkpoint_manifest_v1", "SAC checkpoint manifest is an active resumable artifact schema", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/sac/checkpoint.py", "sac_masked_categorical_residual_v5", "V5 checkpoint validation preserves the bounded residual-policy identity", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/train_discrete_sac.py", "bc_initialized_discrete_sac_preregistration_v1", "SAC bounded experiment preregistration artifact identity", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/train_discrete_sac.py", "bc_initialized_discrete_sac_rollout_summary_v1", "SAC online rollout summary artifact identity", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/sac/checkpoint.py", "bc_initialized_discrete_sac_checkpoint_state_v2", "SAC deterministic replay checkpoint state contract", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/sac/diagnostics.py", "bc_initialized_discrete_sac_update_journal_v2", "SAC append-only deterministic update journal artifact", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/sac/runtime.py", "bc_initialized_discrete_sac_runtime_state_v2", "SAC resumable runtime state evidence", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/sac/runtime.py", "bc_initialized_discrete_sac_transition_order_v2", "SAC committed transition ordering evidence", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/sac/network.py", "bc_initialized_discrete_sac_kl_sentinel_v4", "SAC V4 fixed pre-Actor KL sentinel contract", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("python/planning/sac/runtime.py", "bc_initialized_discrete_sac_sentinel_manifest_v4", "SAC V4 immutable sentinel manifest artifact", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/replay_discrete_sac.py", "bc_initialized_discrete_sac_update_journal_v2", "SAC offline exact replay consumes the durable update journal", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/replay_discrete_sac.py", "bc_initialized_discrete_sac_exact_replay_result_v2", "SAC exact replay diagnostic result artifact", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/train_discrete_sac.py", "bc_initialized_discrete_sac_determinism_contract_v2", "SAC deterministic replay experiment contract", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/train_discrete_sac.py", "bc_initialized_discrete_sac_checkpoint_state_v2", "SAC checkpoint state evidence artifact", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/train_discrete_sac.py", "bc_initialized_discrete_sac_rng_state_manifest_v2", "SAC RNG capture manifest artifact", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/train_discrete_sac.py", "bc_initialized_discrete_sac_rollback_audit_v2", "SAC rejected proposal rollback audit artifact", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/train_discrete_sac.py", "bc_initialized_discrete_sac_kl_trust_region_contract_v4", "SAC V4 fixed-factor KL trust-region artifact", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/train_discrete_sac.py", "bc_initialized_discrete_sac_backtracking_statistics_v4", "SAC V4 backtracking statistics artifact", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/train_discrete_sac.py", "bc_initialized_discrete_sac_optimizer_momentum_metrics_v4", "SAC V4 optimizer momentum diagnostics artifact", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/train_discrete_sac.py", "pre_actor_unique_state_observation_v4", "SAC V4 fixed sentinel selection identity", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/train_discrete_sac.py", "bc_residual_online_discrete_sac_actor_contract_v5", "V5 frozen-BC residual actor contract artifact", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/train_discrete_sac.py", "bc_residual_online_discrete_sac_kl_bound_v5", "V5 residual masked-KL bound artifact", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/train_discrete_sac.py", "bc_residual_online_discrete_sac_residual_statistics_v5", "V5 residual statistics artifact", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/train_discrete_sac.py", "source_v3", "V5 startup regression reads the fixed V3 crossing evidence", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/train_discrete_sac.py", "not_recomputed_in_v5", "V5 records that the historical V3 crossing is reused rather than recomputed", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/train_discrete_sac.py", "test_sac_residual_v5", "V5 focused regression test is recorded in the source identity manifest", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/audit_sac_trust_region_v4.py", "audit_sac_trust_region_v4", "SAC V4 offline trust-region regression entrypoint", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/audit_sac_trust_region_v4.py", "bc_initialized_discrete_sac_kl_trust_region_v4_crossing_regression", "SAC V4 offline crossing regression artifact", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/replay_discrete_sac.py", "bc_initialized_discrete_sac_one_step_counterfactual_v2", "SAC one-step causal counterfactual artifact", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/replay_discrete_sac.py", "bc_initialized_discrete_sac_root_cause_v2", "SAC exact-spike root-cause artifact", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/audit_sac_first_kl_crossing.py", "bc_initialized_discrete_sac_first_kl_crossing_v3", "SAC fixed-sentinel first-KL-crossing audit identity", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/audit_sac_first_kl_crossing.py", "bc_initialized_discrete_sac_sentinel_manifest_v3", "SAC pre-Actor fixed sentinel manifest", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/audit_sac_first_kl_crossing.py", "bc_initialized_discrete_sac_sentinel_trajectory_v3", "SAC fixed-sentinel policy-drift trajectory artifact", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/audit_sac_first_kl_crossing.py", "bc_initialized_discrete_sac_first_crossing_v3", "SAC first KL crossing result artifact", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/audit_sac_first_kl_crossing.py", "bc_initialized_discrete_sac_crossing_gradient_v3", "SAC first-crossing gradient decomposition artifact", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/audit_sac_first_kl_crossing.py", "bc_initialized_discrete_sac_one_step_counterfactual_v3", "SAC R0-R8 first-crossing counterfactual artifact", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/audit_sac_first_kl_crossing.py", "bc_initialized_discrete_sac_cumulative_ablation_v3", "SAC cumulative actor-ablation replay artifact", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/audit_sac_first_kl_crossing.py", "bc_initialized_discrete_sac_transaction_ordering_audit_v3", "SAC transaction ordering audit artifact", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/audit_sac_first_kl_crossing.py", "bc_initialized_discrete_sac_rollback_regression_v3", "SAC rollback regression artifact", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/audit_sac_first_kl_crossing.py", "bc_initialized_discrete_sac_root_cause_v3", "SAC first-crossing root-cause artifact", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/audit_sac_first_kl_crossing.py", "bc_initialized_discrete_sac_batch_vs_sentinel_kl_v3", "SAC minibatch composition versus fixed sentinel KL artifact", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/audit_sac_first_kl_crossing.py", "bc_initialized_discrete_sac_update_journal_v2", "SAC first-crossing audit consumes the frozen V2 update journal", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/audit_sac_first_kl_crossing.py", "one_step_counterfactual_v3", "SAC first-crossing output filename is an isolated diagnostic artifact", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/audit_sac_first_kl_crossing.py", "test_sac_deterministic_replay_v2", "SAC first-crossing source identity manifest records the deterministic replay regression test", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/audit_sac_entropy_floor_v6.py", "bc_initialized_discrete_sac_update_journal_v2", "V6 entropy-floor audit consumes the frozen V2 update journal without changing production replay", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/audit_sac_entropy_floor_v6.py", "discrete_sac_entropy_floor_root_cause_v6_input_identity_v1", "V6 input identity records the read-only V5 evidence boundary", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/audit_sac_entropy_floor_v6.py", "discrete_sac_entropy_floor_gate_contract_audit_v1", "V6 records the production entropy gate semantics as a diagnostic contract", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/audit_sac_entropy_floor_v6.py", "discrete_sac_mask_entropy_feasibility_v1", "V6 records mathematical action-mask entropy feasibility without changing the gate", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/audit_sac_entropy_floor_v6.py", "bc_initialized_discrete_sac_entropy_floor_exact_replay_v1", "V6 exact replay result is an isolated diagnostic artifact", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/audit_sac_entropy_floor_v6.py", "discrete_sac_batch_vs_sentinel_entropy_v1", "V6 separates training-batch composition from fixed-sentinel policy drift", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/audit_sac_entropy_floor_v6.py", "discrete_sac_entropy_reference_check_v1", "V6 records the independent masked-entropy reference comparison", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
    _entry("scripts/audit_sac_entropy_floor_v6.py", "discrete_sac_entropy_floor_root_cause_v6", "V6 root-cause classification is diagnostic-only and cannot promote production", "NEVER_ARTIFACT_SCHEMA_COMPATIBILITY"),
)


def _allowlist_by_key():
    result = {}
    for entry in ALLOWLIST:
        key = (entry["path"], entry["symbol"])
        if key in result:
            raise AssertionError("duplicate versioned-name allowlist entry: {}".format(key))
        if not entry["why_allowed"] or not entry["removal_phase"]:
            raise AssertionError("incomplete versioned-name allowlist entry: {}".format(key))
        result[key] = entry
    return result


def main() -> int:
    root = Path(__file__).resolve().parents[2]
    allowlist = _allowlist_by_key()
    files = []
    for directory in ("python", "scripts", "config"):
        files.extend((root / directory).rglob("*.py"))
        files.extend((root / directory).rglob("*.sh"))
    files.append(root / "tests" / "benchmark_hotpaths.py")

    violations = []
    observed = set()
    for path in sorted(files):
        text = path.read_text(encoding="utf-8")
        relative_path = path.relative_to(root).as_posix()
        for match in VERSIONED_NAME.finditer(text):
            symbol = match.group(0)
            key = (relative_path, symbol)
            observed.add(key)
            if key in allowlist:
                continue
            line = text.count("\n", 0, match.start()) + 1
            violations.append(
                "{}:{}:{}".format(relative_path, line, symbol)
            )
    unexplained = sorted(observed.difference(allowlist))
    if violations or unexplained:
        raise AssertionError(
            "unexplained versioned business names: {}".format(
                "; ".join(violations)
            )
        )
    print("SEMANTIC_CONTRACT_NAMING=PASS")
    print("VERSIONED_NAME_ALLOWLIST_ENTRIES={}".format(len(allowlist)))
    print("UNEXPLAINED_VERSIONED_BUSINESS_NAME_COUNT=0")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
