#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Visualize XMflight 105-action motion primitive library.

Modes:
  1) RViz MarkerArray:
       rosrun planning visualize_motion_primitives.py --rviz --frame base_link

  2) Static PNG:
       rosrun planning visualize_motion_primitives.py --save-png /tmp/motion_primitives_105.png --dpi 600

Topics:
  /xm/mpl_library_markers    visualization_msgs/MarkerArray

Requires:
  - data/motion_primitives/motion_primitives_105.npz generated by:
      rosrun planning generate_motion_primitives.py
"""

from __future__ import annotations

from pathlib import Path



import argparse
import time

import numpy as np
from typing import Any

try:
    import rospy
    from geometry_msgs.msg import Point
    from std_msgs.msg import ColorRGBA
    from visualization_msgs.msg import Marker, MarkerArray
except Exception:
    rospy = None
    Point = None
    ColorRGBA = None
    Marker = None
    MarkerArray = None

from planning.primitives.library import MotionPrimitiveLibrary


def color_by_z(
    z: float,
    z_min: float = -0.6,
    z_max: float = 0.6,
    alpha: float = 1.0,
    as_ros_msg: bool = False,
):
    """Blue->cyan->green->yellow->red colormap.

    Returns:
      - tuple(r,g,b,a) for matplotlib/PNG
      - std_msgs/ColorRGBA only when as_ros_msg=True
    """
    t = (float(z) - float(z_min)) / max(1e-6, float(z_max) - float(z_min))
    t = max(0.0, min(1.0, t))

    if t < 0.25:
        r, g, b = 0.0, 4.0 * t, 1.0
    elif t < 0.50:
        r, g, b = 0.0, 1.0, 1.0 - 4.0 * (t - 0.25)
    elif t < 0.75:
        r, g, b = 4.0 * (t - 0.50), 1.0, 0.0
    else:
        r, g, b = 1.0, 1.0 - 4.0 * (t - 0.75), 0.0

    r = float(max(0.0, min(1.0, r)))
    g = float(max(0.0, min(1.0, g)))
    b = float(max(0.0, min(1.0, b)))
    a = float(alpha)

    if as_ros_msg:
        if ColorRGBA is None:
            raise RuntimeError("std_msgs/ColorRGBA is unavailable")
        c = ColorRGBA()
        c.r = r
        c.g = g
        c.b = b
        c.a = a
        return c

    return (r, g, b, a)


def make_line_marker(
    action_id: int,
    path: np.ndarray,
    meta: dict,
    frame: str,
    line_width: float,
    alpha: float,
):
    marker = Marker()
    marker.header.frame_id = frame
    marker.header.stamp = rospy.Time.now()
    marker.ns = "mpl_paths"
    marker.id = int(action_id)
    marker.type = Marker.LINE_STRIP
    marker.action = Marker.ADD
    marker.pose.orientation.w = 1.0
    marker.scale.x = float(line_width)
    marker.color = color_by_z(float(meta["vertical_endpoint_m"]), alpha=alpha, as_ros_msg=True)

    marker.points = []
    for p in path:
        q = Point()
        q.x = float(p[0])
        q.y = float(p[1])
        q.z = float(p[2])
        marker.points.append(q)

    return marker


def make_endpoint_marker(
    action_id: int,
    endpoint: np.ndarray,
    meta: dict,
    frame: str,
    radius: float,
    alpha: float,
):
    marker = Marker()
    marker.header.frame_id = frame
    marker.header.stamp = rospy.Time.now()
    marker.ns = "mpl_endpoints"
    marker.id = 1000 + int(action_id)
    marker.type = Marker.SPHERE
    marker.action = Marker.ADD
    marker.pose.position.x = float(endpoint[0])
    marker.pose.position.y = float(endpoint[1])
    marker.pose.position.z = float(endpoint[2])
    marker.pose.orientation.w = 1.0
    marker.scale.x = float(radius)
    marker.scale.y = float(radius)
    marker.scale.z = float(radius)
    marker.color = color_by_z(float(meta["vertical_endpoint_m"]), alpha=alpha, as_ros_msg=True)

    return marker


def make_text_marker(
    action_id: int,
    endpoint: np.ndarray,
    meta: dict,
    frame: str,
    text_size: float,
):
    marker = Marker()
    marker.header.frame_id = frame
    marker.header.stamp = rospy.Time.now()
    marker.ns = "mpl_action_ids"
    marker.id = 2000 + int(action_id)
    marker.type = Marker.TEXT_VIEW_FACING
    marker.action = Marker.ADD
    marker.pose.position.x = float(endpoint[0])
    marker.pose.position.y = float(endpoint[1])
    marker.pose.position.z = float(endpoint[2] + 0.12)
    marker.pose.orientation.w = 1.0
    marker.scale.z = float(text_size)
    marker.color.r = 1.0
    marker.color.g = 1.0
    marker.color.b = 1.0
    marker.color.a = 0.90
    marker.text = str(action_id)

    return marker


def make_axis_marker(frame: str):
    arr = MarkerArray()

    specs = [
        ("x_forward", 3000, (1.0, 0.0, 0.0), (1.2, 0.0, 0.0)),
        ("y_left", 3001, (0.0, 1.0, 0.0), (0.0, 1.2, 0.0)),
        ("z_up", 3002, (0.0, 0.0, 1.0), (0.0, 0.0, 0.8)),
    ]

    for ns, mid, color, end in specs:
        m = Marker()
        m.header.frame_id = frame
        m.header.stamp = rospy.Time.now()
        m.ns = ns
        m.id = mid
        m.type = Marker.ARROW
        m.action = Marker.ADD
        m.pose.orientation.w = 1.0
        m.scale.x = 0.035
        m.scale.y = 0.08
        m.scale.z = 0.08
        m.color.r = color[0]
        m.color.g = color[1]
        m.color.b = color[2]
        m.color.a = 1.0

        p0 = Point()
        p0.x = 0.0
        p0.y = 0.0
        p0.z = 0.0

        p1 = Point()
        p1.x, p1.y, p1.z = end

        m.points = [p0, p1]
        arr.markers.append(m)

    return arr


def build_marker_array(lib: MotionPrimitiveLibrary, args) -> Any:
    arr = MarkerArray()

    if args.clear:
        for ns_base, offset in [
            ("mpl_paths", 0),
            ("mpl_endpoints", 1000),
            ("mpl_action_ids", 2000),
        ]:
            for i in range(lib.num_actions):
                m = Marker()
                m.header.frame_id = args.frame
                m.header.stamp = rospy.Time.now()
                m.ns = ns_base
                m.id = offset + i
                m.action = Marker.DELETE
                arr.markers.append(m)

    selected = parse_action_filter(args.actions, lib.num_actions)

    for action_id in selected:
        path = lib.reference_path(action_id)
        endpoint = path[-1]
        meta = lib.action_metadata(action_id)

        arr.markers.append(
            make_line_marker(
                action_id,
                path,
                meta,
                args.frame,
                args.line_width,
                args.alpha,
            )
        )

        if args.endpoints:
            arr.markers.append(
                make_endpoint_marker(
                    action_id,
                    endpoint,
                    meta,
                    args.frame,
                    args.endpoint_radius,
                    args.alpha,
                )
            )

        if args.labels:
            arr.markers.append(
                make_text_marker(
                    action_id,
                    endpoint,
                    meta,
                    args.frame,
                    args.text_size,
                )
            )

    if args.axes:
        arr.markers.extend(make_axis_marker(args.frame).markers)

    return arr


def parse_action_filter(text: str, n: int):
    if not text or text.lower() == "all":
        return list(range(n))

    out = []

    for part in text.split(","):
        part = part.strip()

        if "-" in part:
            a, b = part.split("-", 1)
            out.extend(range(int(a), int(b) + 1))
        else:
            out.append(int(part))

    out = sorted(set(i for i in out if 0 <= i < n))

    return out


def run_rviz(args):
    if rospy is None:
        raise RuntimeError("rospy/visualization_msgs are not available")

    rospy.init_node("planning_mpl_visualizer", anonymous=True)
    lib = MotionPrimitiveLibrary()

    pub = rospy.Publisher(args.topic, MarkerArray, queue_size=1, latch=True)

    arr = build_marker_array(lib, args)

    time.sleep(0.5)
    pub.publish(arr)

    print("MOTION_PRIMITIVE_RVIZ_MARKERS=PASS")
    print("  topic:", args.topic)
    print("  frame:", args.frame)
    print("  actions:", len(parse_action_filter(args.actions, lib.num_actions)))
    print("  markers:", len(arr.markers))
    print("  color: z_end height, blue=down red=up")
    print("  line_width:", args.line_width)

    if args.once:
        rospy.sleep(1.0)
        return

    rate = rospy.Rate(args.publish_hz)

    while not rospy.is_shutdown():
        arr = build_marker_array(lib, args)
        pub.publish(arr)
        rate.sleep()


def save_png(args):
    import matplotlib

    matplotlib.use("Agg")

    import matplotlib.pyplot as plt

    lib = MotionPrimitiveLibrary()
    actions = parse_action_filter(args.actions, lib.num_actions)

    # 600 dpi 输出尺寸：
    # figsize=(12, 8), dpi=600 => 7200 × 4800 px
    fig = plt.figure(figsize=(args.fig_width, args.fig_height), dpi=args.dpi)
    ax = fig.add_subplot(111, projection="3d")

    z_min = float(np.min(lib.z_end))
    z_max = float(np.max(lib.z_end))

    for action_id in actions:
        p = lib.reference_path(action_id)
        meta = lib.action_metadata(action_id)

        rgba = color_by_z(
            float(meta["vertical_endpoint_m"]),
            z_min,
            z_max,
            alpha=args.alpha,
        )

        ax.plot(
            p[:, 0],
            p[:, 1],
            p[:, 2],
            linewidth=args.png_line_width,
            color=rgba[:3],
            alpha=args.alpha,
        )

        if args.endpoints:
            ax.scatter(
                [p[-1, 0]],
                [p[-1, 1]],
                [p[-1, 2]],
                s=args.endpoint_size,
                color=rgba[:3],
                alpha=args.alpha,
            )

        if args.labels:
            ax.text(
                p[-1, 0],
                p[-1, 1],
                p[-1, 2],
                str(action_id),
                fontsize=args.label_fontsize,
            )

    ax.set_title("XMflight 105 Motion Primitive Library")
    ax.set_xlabel("x forward (m)")
    ax.set_ylabel("y left (m)")
    ax.set_zlabel("z up (m)")

    ax.set_xlim(0.0, float(np.max(lib.pos_ref[:, :, 0])) + 0.2)

    y_abs = float(np.max(np.abs(lib.pos_ref[:, :, 1]))) + 0.2
    z_abs = float(np.max(np.abs(lib.pos_ref[:, :, 2]))) + 0.2

    ax.set_ylim(-y_abs, y_abs)
    ax.set_zlim(-z_abs, z_abs)

    ax.view_init(elev=args.elev, azim=args.azim)
    ax.grid(True)

    path = Path(args.save_png).expanduser().resolve()
    path.parent.mkdir(parents=True, exist_ok=True)

    fig.tight_layout()

    # 不加 bbox_inches="tight"，避免改变最终像素尺寸
    fig.savefig(path, dpi=args.dpi)

    plt.close(fig)

    width_px = int(round(args.fig_width * args.dpi))
    height_px = int(round(args.fig_height * args.dpi))

    print("MOTION_PRIMITIVE_PNG_SAVE=PASS")
    print("  path:", path)
    print("  actions:", len(actions))
    print("  dpi:", args.dpi)
    print("  figsize_inch: {:.2f} x {:.2f}".format(args.fig_width, args.fig_height))
    print("  expected_pixels: {} x {}".format(width_px, height_px))


def print_stats(args):
    lib = MotionPrimitiveLibrary()

    print("MOTION_PRIMITIVE_VISUALIZATION_STATS")
    print("  actions:", lib.num_actions)
    print("  frames:", lib.frames)
    print("  duration:", lib.duration_s)
    print("  dt:", lib.control_dt_s)

    print(
        "  x range: [{:.3f}, {:.3f}]".format(
            float(lib.pos_ref[:, :, 0].min()),
            float(lib.pos_ref[:, :, 0].max()),
        )
    )

    print(
        "  y range: [{:.3f}, {:.3f}]".format(
            float(lib.pos_ref[:, :, 1].min()),
            float(lib.pos_ref[:, :, 1].max()),
        )
    )

    print(
        "  z range: [{:.3f}, {:.3f}]".format(
            float(lib.pos_ref[:, :, 2].min()),
            float(lib.pos_ref[:, :, 2].max()),
        )
    )

    print("  y_end:", np.round(lib.y_end.reshape(15, 7)[:, 3], 3).tolist())
    print("  z_end:", np.round(lib.z_end[:7], 3).tolist())


def main():
    parser = argparse.ArgumentParser()

    parser.add_argument("--rviz", action="store_true", help="Publish MarkerArray for RViz.")
    parser.add_argument(
        "--save-png",
        default="data/motion_primitives/motion_primitives_105.png",
        help="Save static 3D plot to PNG (default: data/motion_primitives/motion_primitives_105.png).",
    )
    parser.add_argument("--stats", action="store_true", help="Print library statistics.")

    parser.add_argument("--topic", default="/xm/mpl_library_markers")
    parser.add_argument(
        "--frame",
        default="base_link",
        help="base_link: relative to UAV; map: fixed at world origin.",
    )

    parser.add_argument(
        "--actions",
        default="all",
        help="all, 52, 0,6,52, or range like 49-55",
    )

    parser.add_argument("--endpoints", dest="endpoints", action="store_true", help="Show endpoint spheres.")
    parser.add_argument("--no-endpoints", dest="endpoints", action="store_false", help="Hide endpoint spheres.")
    parser.add_argument("--labels", action="store_true", help="Show action_id text labels.")
    parser.add_argument("--axes", action="store_true", default=True)

    parser.add_argument("--line-width", type=float, default=0.025)
    parser.add_argument("--endpoint-radius", type=float, default=0.08)
    parser.add_argument("--text-size", type=float, default=0.12)
    parser.add_argument("--alpha", type=float, default=0.95)

    parser.add_argument("--publish-hz", type=float, default=2.0)
    parser.add_argument("--once", action="store_true", help="Publish once and exit.")
    parser.add_argument("--clear", action="store_true")

    parser.add_argument("--elev", type=float, default=28.0)
    parser.add_argument("--azim", type=float, default=-62.0)

    # PNG 输出参数
    parser.add_argument("--dpi", type=int, default=600, help="Output PNG DPI.")
    parser.add_argument("--fig-width", type=float, default=12.0, help="Figure width in inches.")
    parser.add_argument("--fig-height", type=float, default=8.0, help="Figure height in inches.")
    parser.add_argument("--png-line-width", type=float, default=1.4, help="PNG line width.")
    parser.add_argument("--endpoint-size", type=float, default=8.0, help="PNG endpoint marker size.")
    parser.add_argument("--label-fontsize", type=float, default=5.0, help="PNG label font size.")

    parser.set_defaults(endpoints=True)
    args = parser.parse_args()

    if args.stats:
        print_stats(args)

    if args.save_png:
        save_png(args)

    if args.rviz:
        run_rviz(args)

    if not args.rviz and not args.save_png and not args.stats:
        print_stats(args)


if __name__ == "__main__":
    main()
